apiVersion: v1
kind: Service
metadata:
  name: botit-app-service
spec:
  selector:
    app: botit-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
  type: NodePort